//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public int ID_MonAn { get; set; }
        public System.DateTime NgayAD { get; set; }
        public Nullable<long> GiaBan { get; set; }
        public Nullable<long> GiaKhuyenMai { get; set; }
    
        public virtual MonAn MonAn { get; set; }
    }
}
