//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int ID_PhieuNhap { get; set; }
        public int ID_NguyenLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> GiaNhap { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
