//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietOrder
    {
        public int ID_Order { get; set; }
        public int ID_MonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> GiaBan { get; set; }
        public Nullable<long> ThanhTien { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual Order Order { get; set; }
    }
}
