//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.Orders = new HashSet<Order>();
            this.Voucher_KhachHang = new HashSet<Voucher_KhachHang>();
        }
    
        public int ID { get; set; }
        [StringLength(60, ErrorMessage = "Độ dài nhỏ nhất là 3, tối đa là 60", MinimumLength = 3)]
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public string TenKH { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public string GioiTinh { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        [StringLength(60, ErrorMessage = "Độ dài nhỏ nhất là 3, tối đa là 60", MinimumLength = 3)]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        [Phone(ErrorMessage = "Vui lòng nhập đúng định dạng số điện thoại")]
        public string SDT { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        [EmailAddress(ErrorMessage = "Vui lòng nhập đúng định dạng email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public string MatKhau { get; set; }
        //[Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public string Token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher_KhachHang> Voucher_KhachHang { get; set; }
    }
}
