//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.BangGias = new HashSet<BangGia>();
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietOrders = new HashSet<ChiTietOrder>();
            this.ThanhPhanMonAns = new HashSet<ThanhPhanMonAn>();
        }
    
        public int ID { get; set; }
        public string TenMA { get; set; }
        public string Anh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> ID_LoaiMA { get; set; }
        public Nullable<long> GiaBan { get; set; }
        public Nullable<long> GiaKhuyenMai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangGia> BangGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietOrder> ChiTietOrders { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhPhanMonAn> ThanhPhanMonAns { get; set; }
    }
}
