//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ChiTietOrders = new HashSet<ChiTietOrder>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string DiaChi { get; set; }
        //[Required(ErrorMessage = "Vui lòng không bỏ trống")]
        //[Phone(ErrorMessage = "Vui lòng nhập đúng định dạng số điện thoại")]
        public string SDT { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public string Email { get; set; }
        //[StringLength(60, ErrorMessage = "Độ dài nhỏ nhất là 3, tối đa là 60", MinimumLength = 3)]
        //[Required(ErrorMessage = "Vui lòng không bỏ trống")]
        public string TenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietOrder> ChiTietOrders { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
