//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPhanMonAn
    {
        public int ID_MonAn { get; set; }
        public int ID_NguyenLieu { get; set; }
        public Nullable<int> DinhLuong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
