//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_KhachHang
    {
        public string ID_Voucher { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<System.DateTime> NgayDoi { get; set; }
        public Nullable<System.DateTime> NgaySD { get; set; }
        public string MaVoucher { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
