//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucAnNhanh.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-K9NJ77AV\\SQLEXPRESS;Initial Catalog=ThucAnNhanh;User ID=sa;Pas" +
            "sword=sa2019")]
        public string ChuoiKetNoi {
            get {
                return ((string)(this["ChuoiKetNoi"]));
            }
            set {
                this["ChuoiKetNoi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=45.119.82.72;Initial Catalog=ThucAnNhanh;User ID=khd;Password=!151020" +
            "00Duong")]
        public string ChuoiKetNoi2 {
            get {
                return ((string)(this["ChuoiKetNoi2"]));
            }
            set {
                this["ChuoiKetNoi2"] = value;
            }
        }
    }
}
